sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: nightly

install:
  - bash ./travis/async.sh
  - travis_retry composer update -n $DEPS

script:
  - ./vendor/bin/phpunit -c ./test/phpunit.xml

notifications:
  email: false
